server:
  port: 8085

# spring properties
spring:
  application:
    name: CLOUD-CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RevulaVishnu/tweet-app-cloud-config-server.git
          cloneOnStart: true

#Eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


logging:
  file:
    path: './logs/logs'
    name: ${logging.file.path}/my-app.log
  level:
    org.springframework.web: ERROR

management:
  endpoints:
    web:
      exposure:
        include: "*"