version: "3"
services:
  eureka-server:
    image: 572327248494.dkr.ecr.us-east-1.amazonaws.com/tweet-app:eureka-server
    restart: always
    ports:
      - 8761:8761
    networks:
      - tweet-network

  api-gateway:
    image: 572327248494.dkr.ecr.us-east-1.amazonaws.com/tweet-app:api-gateway
    restart: always
    ports:
      - 8084:8084
    networks:
      - tweet-network
    depends_on:
      - eureka-server

  auth-service:
    image: 572327248494.dkr.ecr.us-east-1.amazonaws.com/tweet-app:auth-service
    restart: always
    ports:
      - 8081:8081
    networks:
      - tweet-network
    depends_on:
      - api-gateway
      - mongo_db

  tweet-service:
    image: 572327248494.dkr.ecr.us-east-1.amazonaws.com/tweet-app:tweet-service
    restart: always
    ports:
      - 8082:8082
    networks:
      - tweet-network
    depends_on:
      - api-gateway
      - auth-service
      - mongo_db

  user-service:
    image: 572327248494.dkr.ecr.us-east-1.amazonaws.com/tweet-app:user-service
    restart: always
    ports:
      - 8083:8083
    networks:
      - tweet-network
    depends_on:
      - api-gateway
      - auth-service
      - mongo_db

  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017

networks:
  tweet-network:
    driver: bridge
