# server properties
server:
  port: 8082

mq:
  token: 'token'
  authStatus: 'status'

# spring properties
spring:
  rabbitmq:
    host: rabbitmq
  application:
    name: TWEET-SERVICE
    main:
      allow-bean-definition-overriding: true
  data:
    mongodb:
      #      url: mongodb+srv://vishnurevula:vinay1@vishnu-db.rcsucd3.mongodb.net/?retryWrites=true&w=majority
      #      url: mongodb://localhost/tweet-app
      database: tweet-app
      port: 27017
      host: mongo_db
      repositories:
        enables: true


#Eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  file:
    path: './logs/logs'
    name: ${logging.file.path}/my-app.log
  level:
    org.springframework.web: ERROR
management:
  endpoints:
    web:
      exposure:
        include: "*"