# server properties
server:
  port: 8083
  data.mongodb.authentication-database=admin
spring.data.mongodb.username=root
spring.data.mongodb.password=root
spring.data.mongodb.database=user_db
spring.data.mongodb.port=27017
spring.data.mongodb.host=localhost

# spring properties
spring:
  application:
    name: USER-SERVICE
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      database: tweet-app
      port: 27017
      host: localhost

#Eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    '[org.springframework.web]': ERROR
    '[com.cognizant.user-service]': DEBUG